ALTER SESSION SET STATISTICS_LEVEL = ALL;

WITH JOB_SUMSAL AS (SELECT JOB, SUM(SAL) as total
                        FROM EMP
                        GROUP BY JOB)
SELECT JOB, total
    FROM JOB_SUMSAL
    WHERE total > (SELECT AVG(total)
                    FROM JOB_SUMSAL);

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL,NULL,'ALLSTATS LAST -ROWS +PREDICATE'));