-- 100) 실수로 지운 데이터 복구하기 (2) (FLASHBACK TABLE)
ALTER TABLE emp ENABLE ROW MOVEMENT;

FLASHBACK TABLE emp TO TIMESTAMP (SYSTIMESTAMP - INTERVAL '5' MINUTE);

SELECT row_movement
  FROM user_tables
  WHERE table_name = 'EMP';
  
  
-- 특정시점으로 FLASHBACK
FLASHBACK TABLE emp TO TIMESTAMP
TO_TIMESTAMP('21/04/29 07:20:59', 'RR/MM/DD HH24:MI:SS');