-- 104) 데이터의 품질 높이기 (1) (PRIMARY KEY)
CREATE TABLE DEPT2
(DEPTNO     NUMBER(10) CONSTRAINT DEPT2_DEPTNO_PK   PRIMARY KEY,
 DNAME      VARCHAR2(14),
 LOC        VARCHAR2(10));
 
 
-- 제약조건 확인
SELECT a.constraint_name, a.constraint_type, b.column_name
  FROM USER_CONSTRAINTS a, USER_CONS_COLUMNS b
  WHERE a.TABLE_NAME = 'DEPT2'
  AND a.CONSTRAINT_NAME = b.CONSTRAINT_NAME;
  
-- 제약조건 생성
ALTER TABLE DEPT2
  ADD CONSTRAINT DEPT2_DEPTNO_PK PRIMARY KEY(DEPTNO);
  
  
INSERT INTO DEPT2 VALUES(10, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT2 VALUES(10, NULL, 'DALLAS');           --> 오류!) ORA-00001: 무결성 제약 조건(SCOTT.DEPT2_DEPTNO_PK)에 위배됩니다
commit;

SELECT * FROM DEPT2;