-- 데이터의 품질 높이기 (5) (FOREIGN KEY)
CREATE TABLE DEPT7
(   DEPTNO      NUMBER(10) CONSTRAINT DEPT7_DEPTNO_PK PRIMARY KEY,
    DNAME       VARCHAR2(14),
    LOC         VARCHAR2(10));
    
CREATE TABLE EMP7
(   EMPNO       NUMBER(10),
    ENAME       VARCHAR2(20),
    SAL         NUMBER(10),
    DEPTNO      NUMBER(10) CONSTRAINT EMP7_DEPTNO_FK REFERENCES DEPT7(DEPTNO));
    
-- 특정컬럼에 데이터를 입력할 때 다른 테이블의 데이터를 참조해서 해당되는 데이터만 허용하고자 할 때 FOREIGN KEY 제약을 사용

-- 제약조건 삭제시
ALTER TABLE DEPT7
 DROP CONSTRAINT DEPT7_DEPTNO_PK;       -- ORA-02273: 고유/기본 키가 외부 키에 의해 참조되었습니다.
-- 자식 테이블인 EMP7 테이블이 부모 테이블인 DEPT7 테이블을 참조하고 있기 때문에 다음과 같이 CASCADE를 사용해야 함
ALTER TABLE DEPT7
 DROP CONSTRAINT DEPT7_DEPTNO_PK CASCADE;   --> 성공!
 
commit;

SELECT a.constraint_name, a.constraint_type, b.column_name
  FROM USER_CONSTRAINTS a, USER_CONS_COLUMNS b
  WHERE a.TABLE_NAME = 'EMP8'
  AND a.CONSTRAINT_NAME = b.CONSTRAINT_NAME;
  
ALTER TABLE DEPT7
  ADD CONSTRAINT DEPT7_DEPTNO_PK PRIMARY KEY(DEPTNO);

-- FOREIGN KEY 제약조건 추가
ALTER TABLE EMP7
  ADD CONSTRAINT EMP7_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT7(DEPTNO);